[package]
name = "steam-db-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["json"] }
rusqlite = "0.37.0"
serde = "1.0.228"
tokio = { version = "1.47.1", features = ["full"] }
